import { Opportunity, Badge, Volunteer, RegisteredOpportunity, OpportunityStatus, Review, OpportunityCategory, WorkStyle, ApplicationStatus, ExperienceLevel, TimeFlexibility, ImpactArea, AcademicQualification, ExperienceYears, LanguageLevel, PreferredWorkType, CommitmentDuration } from './types';

export const ENABLE_LINKEDIN_IMPORT = true;

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 11,
    title: 'تطوير هوية بصرية لجمعية خيرية',
    organization: 'جمعية بصمة خير',
    
    // --- Basic Info ---
    workType: 'تصميم جرافيكي',
    workStyle: WorkStyle.REMOTE,
    commitment: '٢٠-٣٠ ساعة خلال ٣ أسابيع',
    applicationDeadline: '2024-11-15',
    status: ApplicationStatus.OPEN,
    skillTags: ['UI/UX', 'Branding', 'Adobe Illustrator'],
    isFeatured: true,

    // --- Detailed Info ---
    // FIX: Joined multi-line string to fix syntax error.
    organizationDescription: 'جمعية بصمة خير هي منظمة غير ربحية تهدف إلى دعم الأسر المحتاجة وتوفير التعليم للأطفال في المناطق النائية.',
    opportunitySummary: 'مساهمة احترافية لتصميم هوية بصرية متكاملة تعكس رؤية ورسالة الجمعية لزيادة الوعي وجذب الداعمين.',
    detailedDescription: 'نبحث عن مصمم مبدع لإنشاء هوية بصرية كاملة تشمل الشعار، لوحة الألوان، الخطوط، وتصاميم المواد التسويقية الأولية. الهدف هو بناء صورة احترافية للجمعية تساعدها في الوصول لشريحة أكبر من المتبرعين والشركاء.',
    volunteerRole: 'مصمم هوية بصرية (Branding Designer)',
    tasks: [
      'تصميم شعار مبتكر ومعبر عن أهداف الجمعية.',
      'تحديد لوحة ألوان وخطوط رسمية للهوية.',
      'تصميم نماذج للمطبوعات (بروشور، بطاقة عمل).',
      'تصميم قوالب لمنصات التواصل الاجتماعي.',
    ],
    expectedDeliverables: [
      'ملف دليل الهوية البصرية (Brand Guidelines).',
      'جميع أصول الشعار بصيغ مختلفة (Vector, PNG).',
      'ملفات التصاميم المصدرية (AI, PSD).',
    ],
    requiredSkills: ['Adobe Illustrator', 'Adobe Photoshop', 'تصميم الشعارات', 'بناء الهوية البصرية'],
    preferredSkills: ['خبرة في تصميم هوية لمنظمات غير ربحية'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-01',
    endDate: '2024-12-21',
    timeCommitmentPerWeek: '٧-١٠ ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: {
      interviewRequired: true,
      ndaRequired: false,
    },
    benefits: [
      'شهادة تطوع احترافية معتمدة.',
      'إضافة المشروع لمعرض الأعمال الخاص بك.',
      'خطاب توصية من إدارة الجمعية.',
    ],
    socialImpact: {
      description: 'الهوية الجديدة ستساهم في تعزيز ثقة الداعمين وزيادة التبرعات، مما يمكّن الجمعية من مساعدة عدد أكبر من الأسر المستفيدة.',
      // FIX: Joined multi-line string to fix syntax error.
      beneficiaries: 'الأسر المحتاجة والأطفال',
    },
    
    // --- Platform & Legacy ---
    applicantsCount: 12,
    category: OpportunityCategory.DESIGN,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=1964&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.8,
    reviewsCount: 4,
    points: 300,
    hours: 30,
  },
  {
    id: 12,
    title: 'تنظيم حملة تنظيف شاطئ نصف القمر',
    organization: 'مبادرة بيئة خضراء',
    workType: 'عمل ميداني',
    workStyle: WorkStyle.ONSITE,
    commitment: 'يوم واحد (8 ساعات)',
    applicationDeadline: '2024-10-20',
    status: ApplicationStatus.OPEN,
    city: 'الدمام',
    skillTags: ['عمل جماعي', 'بيئة', 'تنظيم'],
    isFeatured: false,
    organizationDescription: 'مبادرة شبابية تهدف لزيادة الوعي البيئي والحفاظ على نظافة الشواطئ السعودية.',
    opportunitySummary: 'شاركنا في يوم ممتع ومفيد لتنظيف شاطئ نصف القمر والمساهمة في حماية الحياة البحرية.',
    detailedDescription: 'ندعو جميع محبي البيئة للانضمام إلينا في حملة تنظيف شاملة لشاطئ نصف القمر. سيتم توفير جميع الأدوات اللازمة. هذه فرصة رائعة للتعرف على أصدقاء جدد وإحداث فرق ملموس.',
    volunteerRole: 'عضو فريق التنظيف',
    tasks: ['جمع النفايات من الشاطئ', 'فرز المواد القابلة لإعادة التدوير', 'المساعدة في توعية الزوار بأهمية النظافة'],
    expectedDeliverables: ['شاطئ نظيف', 'زيادة الوعي البيئي بين المشاركين والزوار'],
    requiredSkills: ['اللياقة البدنية الأساسية', 'الالتزام بتعليمات السلامة'],
    preferredSkills: ['خبرة سابقة في حملات مشابهة'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-10-26',
    endDate: '2024-10-26',
    timeCommitmentPerWeek: '8 ساعات',
    timeFlexibility: TimeFlexibility.FIXED,
    eligibility: { minimumAge: 16 },
    benefits: ['شهادة مشاركة', 'وجبة غداء', 'اكتساب أصدقاء جدد'],
    socialImpact: { description: 'الحفاظ على نظافة الشواطئ السعودية وحماية النظام البيئي البحري من التلوث.' },
    applicantsCount: 45,
    category: OpportunityCategory.ENVIRONMENTAL,
    impactArea: ImpactArea.ENVIRONMENT,
    imageUrl: 'https://images.unsplash.com/photo-1617936307394-616abbb52125?q=80&w=2070&auto=format&fit=crop',
    lat: 26.1384,
    lng: 50.1802,
    rating: 4.9,
    reviewsCount: 15,
    points: 100,
    hours: 8,
  },
  {
    id: 13,
    title: 'تطوير موقع إلكتروني لجمعية أيتام',
    organization: 'جمعية بسمة أمل',
    workType: 'تطوير ويب',
    workStyle: WorkStyle.REMOTE,
    commitment: '40 ساعة خلال شهر',
    applicationDeadline: '2024-11-01',
    status: ApplicationStatus.OPEN,
    skillTags: ['React', 'Node.js', 'Frontend', 'Backend'],
    isFeatured: true,
    organizationDescription: 'جمعية بسمة أمل لرعاية الأيتام، تسعى لتوفير بيئة داعمة وكريمة للأطفال الأيتام.',
    opportunitySummary: 'مطلوب مطور ويب محترف لإنشاء موقع إلكتروني تفاعلي للجمعية يسهل عملية التبرع والكفالة.',
    detailedDescription: 'نبحث عن مطور Full-Stack لإنشاء موقع إلكتروني عصري للجمعية من الصفر. سيشمل الموقع صفحات تعريفية، نظام لعرض الأيتام للكفالة، وبوابة تبرع إلكترونية آمنة.',
    volunteerRole: 'مطور ويب Full-Stack',
    tasks: ['تصميم وبناء الواجهات الأمامية (Frontend)', 'تطوير الواجهات الخلفية (Backend) ونظام إدارة المحتوى', 'ربط بوابات الدفع الإلكتروني'],
    expectedDeliverables: ['موقع إلكتروني فعال ومتجاوب', 'لوحة تحكم سهلة الاستخدام لموظفي الجمعية'],
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB'],
    preferredSkills: ['خبرة في أمن المواقع', 'العمل مع بوابات الدفع'],
    experienceLevel: ExperienceLevel.EXPERT,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-10',
    timeCommitmentPerWeek: '10 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: { interviewRequired: true },
    benefits: ['خطاب توصية مميز', 'إضافة المشروع لمعرض الأعمال', 'أثر كبير في تسهيل دعم الأيتام'],
    socialImpact: { description: 'سيساهم الموقع الجديد في زيادة عدد الكفالات والتبرعات بشكل كبير، مما يؤثر إيجابًا على حياة عشرات الأيتام.' },
    applicantsCount: 8,
    category: OpportunityCategory.TECH,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2070&auto=format&fit=crop',
    lat: 21.4858,
    lng: 39.1925,
    rating: 5.0,
    reviewsCount: 1,
    points: 400,
    hours: 40,
  },
  {
    id: 14,
    title: 'حملة توعية بمرض السكري في المراكز الصحية',
    organization: 'وزارة الصحة (شراكة مجتمعية)',
    workType: 'توعية صحية',
    workStyle: WorkStyle.HYBRID,
    commitment: '15 ساعة خلال أسبوعين',
    applicationDeadline: '2024-11-05',
    status: ApplicationStatus.REVIEWING,
    city: 'المدينة المنورة',
    skillTags: ['تواصل', 'صحة عامة', 'تثقيف'],
    isFeatured: false,
    organizationDescription: 'برنامج تطوعي بالتعاون مع وزارة الصحة لرفع مستوى الوعي الصحي في المجتمع.',
    opportunitySummary: 'مشاركة في تنظيم وتفعيل أركان توعوية عن مرض السكري وكيفية الوقاية منه في عدد من المراكز الصحية.',
    detailedDescription: 'نحتاج لمتطوعين شغوفين بالصحة للمساعدة في تقديم معلومات مبسطة للزوار، إجراء قياسات سكر مبدئية (بعد التدريب)، وتوزيع المطويات التثقيفية. العمل يشمل جزءًا من التخطيط عن بعد وجزءًا ميدانيًا.',
    volunteerRole: 'مثقف صحي',
    tasks: ['شرح عوامل الخطورة للإصابة بالسكري', 'المساعدة في فحص السكر', 'الإجابة على أسئلة الجمهور الأساسية'],
    expectedDeliverables: ['توعية ما لا يقل عن 500 زائر', 'تقارير يومية عن الأنشطة'],
    requiredSkills: ['مهارات تواصل ممتازة', 'القدرة على تبسيط المعلومات الطبية'],
    preferredSkills: ['طلاب الكليات الصحية'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-14',
    timeCommitmentPerWeek: '5-7 ساعات',
    timeFlexibility: TimeFlexibility.AS_AGREED,
    eligibility: {},
    benefits: ['شهادة من وزارة الصحة', 'اكتساب خبرة في التثقيف الصحي', 'تدريب متخصص'],
    socialImpact: { description: 'زيادة وعي المجتمع حول مرض السكري، مما يساهم في الكشف المبكر وتقليل المضاعفات.' },
    applicantsCount: 25,
    category: OpportunityCategory.HEALTH,
    impactArea: ImpactArea.HEALTH,
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=2070&auto=format&fit=crop',
    lat: 24.4686,
    lng: 39.6142,
    rating: 4.7,
    reviewsCount: 9,
    points: 150,
    hours: 15,
  },
  {
    id: 15,
    title: 'دروس تقوية لطلاب المرحلة الثانوية (أونلاين)',
    organization: 'منصة علم',
    workType: 'تدريس',
    workStyle: WorkStyle.REMOTE,
    commitment: '25 ساعة (حصتين أسبوعيًا لمدة شهر)',
    applicationDeadline: '2024-10-25',
    status: ApplicationStatus.OPEN,
    skillTags: ['رياضيات', 'فيزياء', 'شرح', 'تعليم'],
    isFeatured: false,
    organizationDescription: 'منصة غير ربحية تقدم الدعم التعليمي للطلاب المحتاجين في جميع أنحاء المملكة.',
    opportunitySummary: 'فرصة للمتخصصين في المواد العلمية لتقديم دروس تقوية أونلاين لطلاب الثانوية العامة، والمساهمة في نجاحهم الأكاديمي.',
    detailedDescription: 'مطلوب متطوعون لتقديم شروحات مبسطة في مواد الرياضيات، الفيزياء، أو الكيمياء عبر منصتنا التعليمية. كل متطوع سيكون مسؤولاً عن مجموعة صغيرة من الطلاب لضمان جودة التعليم.',
    volunteerRole: 'مدرس مواد علمية',
    tasks: ['تحضير وتقديم حصص دراسية تفاعلية', 'الإجابة على استفسارات الطلاب', 'إعداد اختبارات قصيرة لمتابعة التقدم'],
    expectedDeliverables: ['إكمال المنهج المحدد مع الطلاب', 'تحسن ملحوظ في مستوى الطلاب الأكاديمي'],
    requiredSkills: ['إتقان أحد المواد العلمية (رياضيات، فيزياء، كيمياء)', 'مهارات ممتازة في الشرح والتواصل'],
    preferredSkills: ['خبرة سابقة في التدريس'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-01',
    timeCommitmentPerWeek: '6 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: { interviewRequired: true },
    benefits: ['شهادة خبرة في التعليم عن بعد', 'تطوير المهارات التربوية', 'أثر مباشر في مستقبل الطلاب'],
    socialImpact: { description: 'تمكين الطلاب من تحقيق درجات أعلى في اختباراتهم، مما يزيد من فرص قبولهم في الجامعات المرموقة.' },
    applicantsCount: 18,
    category: OpportunityCategory.EDUCATION,
    impactArea: ImpactArea.EDUCATION,
    imageUrl: 'https://images.unsplash.com/photo-1588072432836-e10032774350?q=80&w=2072&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.9,
    reviewsCount: 22,
    points: 250,
    hours: 25,
  },
    {
    id: 16,
    title: 'إدارة حسابات التواصل الاجتماعي لمسابقة رواد الأعمال',
    organization: 'الهيئة العامة للمنشآت الصغيرة والمتوسطة "منشآت"',
    workType: 'تسويق رقمي',
    workStyle: WorkStyle.HYBRID,
    commitment: '35 ساعة على مدى شهرين',
    applicationDeadline: '2024-10-30',
    status: ApplicationStatus.OPEN,
    city: 'الرياض',
    skillTags: ['Social Media', 'Content Creation', 'Marketing'],
    isFeatured: true,
    organizationDescription: 'مسابقة وطنية تهدف إلى دعم وتشجيع رواد الأعمال الشباب في المملكة.',
    opportunitySummary: 'نبحث عن مبدع في إدارة وسائل التواصل الاجتماعي للمساعدة في الترويج للمسابقة وزيادة التفاعل وجذب المشاركين.',
    detailedDescription: 'المتطوع سيكون مسؤولاً عن إنشاء محتوى جذاب، وجدولة المنشورات، والتفاعل مع المتابعين على منصات (X, Instagram, LinkedIn). يتطلب العمل حضور بعض الفعاليات الرئيسية.',
    volunteerRole: 'أخصائي تواصل اجتماعي',
    tasks: ['وضع خطة محتوى أسبوعية', 'تصميم منشورات بسيطة باستخدام Canva', 'كتابة محتوى إعلاني', 'تغطية الفعاليات مباشرة'],
    expectedDeliverables: ['زيادة عدد المتابعين بنسبة 20%', 'تقرير تفاعل أسبوعي', 'محتوى مبتكر يعكس روح المسابقة'],
    requiredSkills: ['إدارة حسابات التواصل الاجتماعي', 'كتابة المحتوى', 'Canva'],
    preferredSkills: ['خبرة في حملات التسويق الرقمي'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية', 'الإنجليزية'],
    startDate: '2024-11-15',
    timeCommitmentPerWeek: '4-5 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: { interviewRequired: true },
    benefits: ['شهادة من "منشآت"', 'بناء شبكة علاقات قوية في بيئة ريادة الأعمال', 'فرصة لحضور فعاليات حصرية'],
    socialImpact: { description: 'المساهمة في نجاح مسابقة وطنية تدعم اقتصاد المملكة وتمكن الشباب السعودي.' },
    applicantsCount: 30,
    category: OpportunityCategory.MARKETING,
    impactArea: ImpactArea.YOUTH,
    imageUrl: 'https://images.unsplash.com/photo-1611162617213-6d22e4ca1c78?q=80&w=1974&auto=format&fit=crop',
    lat: 24.774265,
    lng: 46.738586,
    rating: 4.8,
    reviewsCount: 11,
    points: 350,
    hours: 35,
  },
  {
    id: 17,
    title: 'تصميم مواد إعلانية لمهرجان أبها الثقافي',
    organization: 'هيئة تطوير منطقة عسير',
    workType: 'تصميم جرافيكي',
    workStyle: WorkStyle.REMOTE,
    commitment: '20 ساعة خلال 3 أسابيع',
    applicationDeadline: '2024-11-12',
    status: ApplicationStatus.OPEN,
    city: 'أبها',
    skillTags: ['Photoshop', 'Branding', 'تصميم إعلاني'],
    isFeatured: false,
    organizationDescription: 'مهرجان سنوي يحتفي بالثقافة والفنون في منطقة عسير.',
    opportunitySummary: 'نريد مصممًا موهوبًا لإنشاء تصاميم بصرية تعكس الهوية الفريدة للمهرجان وتجذب الزوار.',
    detailedDescription: 'سيقوم المتطوع بتصميم إعلانات للسوشيال ميديا، بنرات للموقع الإلكتروني، وبعض المواد المطبوعة الصغيرة بناءً على الهوية البصرية الحالية للمهرجان.',
    volunteerRole: 'مصمم جرافيك',
    tasks: ['تصميم 5 قوالب لمنشورات انستغرام', 'تصميم بنر إعلاني للموقع', 'تصميم بطاقة دعوة إلكترونية'],
    expectedDeliverables: ['ملفات التصاميم بصيغ متعددة (JPG, PNG, PDF)', 'الملفات المصدرية (PSD)'],
    requiredSkills: ['Adobe Photoshop', 'فهم مبادئ التصميم'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-20',
    timeCommitmentPerWeek: '7 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: {},
    benefits: ['شهادة شكر من هيئة التطوير', 'إضافة الأعمال للملف الشخصي', 'المساهمة في إنجاح فعالية ثقافية كبرى'],
    socialImpact: { description: 'تعزيز السياحة والثقافة في منطقة عسير من خلال تصاميم جذابة واحترافية.' },
    applicantsCount: 15,
    category: OpportunityCategory.DESIGN,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1541597843336-6e40a74d6c49?q=80&w=1964&auto=format&fit=crop',
    lat: 18.2167,
    lng: 42.5053,
    rating: 4.6,
    reviewsCount: 7,
    points: 200,
    hours: 20,
  },
  {
    id: 18,
    title: 'تحليل بيانات لمشروع بحثي عن الطاقة المتجددة',
    organization: 'جامعة الملك عبدالله للعلوم والتقنية (KAUST)',
    workType: 'تحليل بيانات',
    workStyle: WorkStyle.REMOTE,
    commitment: '50 ساعة خلال شهرين',
    applicationDeadline: '2024-11-25',
    status: ApplicationStatus.OPEN,
    skillTags: ['Python', 'Data Analysis', 'Pandas', 'Matplotlib'],
    isFeatured: true,
    organizationDescription: 'مركز أبحاث الطاقة المتقدمة في جامعة كاوست.',
    opportunitySummary: 'فرصة فريدة للمهتمين بالبيانات والطاقة للمساهمة في مشروع بحثي يهدف لتحليل كفاءة الألواح الشمسية في الظروف المناخية للمملكة.',
    detailedDescription: 'سيقوم المتطوع بالعمل مع فريق بحثي على تحليل مجموعة كبيرة من البيانات المستخرجة من محطات الطاقة الشمسية. المهام تشمل تنظيف البيانات، استكشافها، وتصويرها بيانيًا باستخدام مكتبات Python.',
    volunteerRole: 'محلل بيانات مساعد',
    tasks: ['تنظيف وتجهيز البيانات باستخدام Pandas', 'إجراء تحليل إحصائي استكشافي', 'إنشاء رسوم بيانية تفاعلية باستخدام Matplotlib/Plotly'],
    expectedDeliverables: ['Jupyter Notebook يحتوي على التحليل الكامل', 'تقرير ملخص للنتائج الرئيسية'],
    requiredSkills: ['Python', 'Pandas', 'خبرة في تحليل البيانات'],
    preferredSkills: ['معرفة بمفاهيم الطاقة المتجددة', 'SQL'],
    experienceLevel: ExperienceLevel.EXPERT,
    requiredLanguages: ['الإنجليزية'],
    startDate: '2024-12-01',
    timeCommitmentPerWeek: '6-7 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: { interviewRequired: true, ndaRequired: true },
    benefits: ['شهادة خبرة من كاوست', 'فرصة للنشر المشترك في ورقة علمية', 'اكتساب خبرة بحثية متقدمة'],
    socialImpact: { description: 'المساهمة في تسريع تبني حلول الطاقة النظيفة في المملكة، ودعم الأبحاث الرائدة في هذا المجال.' },
    applicantsCount: 5,
    category: OpportunityCategory.TECH,
    impactArea: ImpactArea.ENVIRONMENT,
    imageUrl: 'https://images.unsplash.com/photo-1509869175199-ce61d2b2a267?q=80&w=2070&auto=format&fit=crop',
    lat: 22.3061,
    lng: 39.1083,
    rating: 5.0,
    reviewsCount: 3,
    points: 500,
    hours: 50,
  },
  {
    id: 19,
    title: 'المشاركة في مبادرة الرياض الخضراء لزراعة الأشجار',
    organization: 'أمانة منطقة الرياض',
    workType: 'زراعة وتشجير',
    workStyle: WorkStyle.ONSITE,
    commitment: 'يوم واحد (6 ساعات)',
    applicationDeadline: '2024-11-20',
    status: ApplicationStatus.OPEN,
    city: 'الرياض',
    skillTags: ['بيئة', 'زراعة', 'عمل ميداني'],
    isFeatured: false,
    organizationDescription: 'جزء من مشروع الرياض الخضراء الذي يهدف لزراعة ملايين الأشجار في المدينة.',
    opportunitySummary: 'كن جزءًا من مستقبل الرياض الأخضر! شارك في زراعة الأشجار في أحد أحياء الرياض وساهم في جعل مدينتنا أكثر جمالاً وصحة.',
    detailedDescription: 'في هذا اليوم التطوعي، سنجتمع لزراعة مئات الشتلات في حديقة عامة. سيتم تقديم شرح عن طريقة الزراعة الصحيحة وأهمية التشجير. لا يتطلب أي خبرة سابقة.',
    volunteerRole: 'مشارك في الزراعة',
    tasks: ['حفر الحفر للشتلات', 'زراعة الشتلات بحسب التوجيهات', 'ري الأشجار المزروعة حديثًا'],
    expectedDeliverables: ['زراعة المنطقة المحددة بالكامل', 'نشر الوعي بأهمية التشجير'],
    requiredSkills: ['الرغبة في العمل في الهواء الطلق', 'القدرة على اتباع التعليمات'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-30',
    timeCommitmentPerWeek: '6 ساعات',
    timeFlexibility: TimeFlexibility.FIXED,
    eligibility: {},
    benefits: ['المساهمة المباشرة في مشروع وطني', 'شهادة تقدير', 'الشعور بالإنجاز'],
    socialImpact: { description: 'زيادة الرقعة الخضراء في الرياض، تحسين جودة الهواء، وتجميل المدينة لسكانها وزوارها.' },
    applicantsCount: 80,
    category: OpportunityCategory.ENVIRONMENTAL,
    impactArea: ImpactArea.ENVIRONMENT,
    imageUrl: 'https://images.unsplash.com/photo-1523348887715-d54d720c6148?q=80&w=2070&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.9,
    reviewsCount: 35,
    points: 80,
    hours: 6,
  },
  {
    id: 20,
    title: 'مساعدة كبار السن في قضاء احتياجاتهم اليومية',
    organization: 'جمعية وقار',
    workType: 'دعم اجتماعي',
    workStyle: WorkStyle.ONSITE,
    commitment: '12 ساعة (زيارتان أسبوعيًا)',
    applicationDeadline: '2024-11-18',
    status: ApplicationStatus.OPEN,
    city: 'مكة المكرمة',
    skillTags: ['رعاية', 'دعم نفسي', 'اجتماعي'],
    isFeatured: false,
    organizationDescription: 'جمعية متخصصة في تقديم الرعاية والدعم لكبار السن في منازلهم.',
    opportunitySummary: 'فرصة لتقديم الدعم والمؤانسة لكبار السن الذين يعيشون بمفردهم، من خلال زيارتهم والمساعدة في بعض المهام البسيطة.',
    detailedDescription: 'سيتم تنسيق المتطوع مع أحد كبار السن للقيام بزيارات دورية. المهام قد تشمل المساعدة في التسوق، قراءة الصحف، أو مجرد الحديث والمؤانسة. الهدف هو التخفيف من شعورهم بالوحدة.',
    volunteerRole: 'صديق مسن',
    tasks: ['الاستماع والتحدث مع كبير السن', 'المساعدة في شراء الحاجيات الأساسية', 'قراءة الكتب أو الصحف لهم'],
    expectedDeliverables: ['بناء علاقة إيجابية مع كبير السن', 'تقديم تقرير بسيط بعد كل زيارة'],
    requiredSkills: ['الاستماع الجيد', 'الصبر', 'التعاطف'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-25',
    timeCommitmentPerWeek: '3 ساعات',
    timeFlexibility: TimeFlexibility.AS_AGREED,
    eligibility: { interviewRequired: true },
    benefits: ['أجر عظيم من الله', 'تنمية مهارات التواصل مع كبار السن', 'شهادة تطوع'],
    socialImpact: { description: 'تحسين الصحة النفسية والجسدية لكبار السن، وتعزيز قيم التكافل الاجتماعي في المجتمع.' },
    applicantsCount: 22,
    category: OpportunityCategory.SOCIAL,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1563241524-11045a31a319?q=80&w=2070&auto=format&fit=crop',
    lat: 21.3891,
    lng: 39.8579,
    rating: 5.0,
    reviewsCount: 18,
    points: 120,
    hours: 12,
  },
  {
    id: 21,
    title: 'تنظيم حملة للتبرع بالدم',
    organization: 'بنك الدم المركزي',
    workType: 'تنظيم فعاليات',
    workStyle: WorkStyle.ONSITE,
    commitment: 'يومان (8 ساعات)',
    applicationDeadline: '2024-12-01',
    status: ApplicationStatus.OPEN,
    city: 'الرياض',
    skillTags: ['تنظيم', 'تواصل', 'عمل ميداني'],
    isFeatured: false,
    organizationDescription: 'حملة دورية لتشجيع المجتمع على التبرع بالدم وتوفير مخزون كاف للمستشفيات.',
    opportunitySummary: 'مطلوب متطوعون للمساعدة في الجوانب التنظيمية لحملة تبرع بالدم في أحد المراكز التجارية الكبرى بالرياض.',
    detailedDescription: 'سيساعد المتطوعون في استقبال المتبرعين، تسجيل بياناتهم، إرشادهم خلال مراحل التبرع، وتقديم الضيافة لهم بعد ذلك. الهدف هو ضمان تجربة سلسة ومريحة للمتبرعين.',
    volunteerRole: 'منظم حملة',
    tasks: ['استقبال وتسجيل المتبرعين', 'توزيع المواد التوعوية', 'المساعدة في تنظيم أماكن الانتظار والراحة'],
    expectedDeliverables: ['تنظيم ناجح لليوم', 'ضمان رضا المتبرعين'],
    requiredSkills: ['مهارات تنظيمية', 'اللباقة وحسن التعامل'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-07',
    timeCommitmentPerWeek: '8 ساعات',
    timeFlexibility: TimeFlexibility.FIXED,
    eligibility: { minimumAge: 18 },
    benefits: ['شهادة تقدير', 'المساهمة في إنقاذ حياة الآخرين'],
    socialImpact: { description: 'زيادة مخزون بنوك الدم، مما يساهم في إنقاذ حياة المرضى والمصابين في الحوادث.' },
    applicantsCount: 38,
    category: OpportunityCategory.HEALTH,
    impactArea: ImpactArea.HEALTH,
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?q=80&w=1964&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.8,
    reviewsCount: 25,
    points: 90,
    hours: 8,
  },
  {
    id: 22,
    title: 'ترجمة محتوى تعليمي للأطفال من الإنجليزية للعربية',
    organization: 'مبادرة إثراء المحتوى العربي',
    workType: 'ترجمة',
    workStyle: WorkStyle.REMOTE,
    commitment: '18 ساعة خلال شهر',
    applicationDeadline: '2024-11-22',
    status: ApplicationStatus.OPEN,
    skillTags: ['ترجمة', 'لغة إنجليزية', 'تعليم'],
    isFeatured: false,
    organizationDescription: 'مبادرة تهدف إلى توفير محتوى تعليمي وترفيهي عالي الجودة باللغة العربية للأطفال.',
    opportunitySummary: 'مطلوب مترجمون متمكنون من اللغتين العربية والإنجليزية لترجمة مقاطع فيديو وقصص تعليمية قصيرة مخصصة للأطفال.',
    detailedDescription: 'سيقوم المتطوع باستلام نصوص باللغة الإنجليزية وترجمتها إلى لغة عربية فصحى ومبسطة تناسب الأطفال، مع مراعاة الجوانب الثقافية. المحتوى يغطي مواضيع مثل العلوم، الفضاء، والطبيعة.',
    volunteerRole: 'مترجم',
    tasks: ['ترجمة 10 نصوص (متوسط 300 كلمة للنص)', 'مراجعة الترجمة لغوياً', 'التأكد من مناسبة المصطلحات للفئة العمرية'],
    expectedDeliverables: ['تسليم النصوص المترجمة في ملفات Word'],
    requiredSkills: ['إتقان اللغتين العربية والإنجليزية', 'مهارات كتابية ممتازة'],
    preferredSkills: ['خبرة في ترجمة محتوى الأطفال'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية', 'الإنجليزية'],
    startDate: '2024-12-01',
    timeCommitmentPerWeek: '4-5 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: {},
    benefits: ['شهادة خبرة في الترجمة', 'تطوير مهارات الترجمة الإبداعية', 'إثراء المحتوى العربي على الإنترنت'],
    socialImpact: { description: 'توفير مصادر تعلم ممتعة وموثوقة للأطفال العرب، مما يساهم في تنمية معارفهم ومهاراتهم اللغوية.' },
    applicantsCount: 40,
    category: OpportunityCategory.EDUCATION,
    impactArea: ImpactArea.EDUCATION,
    imageUrl: 'https://images.unsplash.com/photo-1498674202831-15c0e96b3992?q=80&w=2070&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.7,
    reviewsCount: 13,
    points: 180,
    hours: 18,
  },
  {
    id: 23,
    title: 'ابتكار محتوى لحملة سياحية في العُلا',
    organization: 'الهيئة الملكية لمحافظة العُلا',
    workType: 'صناعة محتوى',
    workStyle: WorkStyle.HYBRID,
    commitment: '25 ساعة خلال 3 أسابيع',
    applicationDeadline: '2024-12-05',
    status: ApplicationStatus.OPEN,
    city: 'العلا',
    skillTags: ['تصوير', 'كتابة إبداعية', 'سياحة'],
    isFeatured: true,
    organizationDescription: 'الجهة المسؤولة عن تطوير العُلا كوجهة سياحية عالمية.',
    opportunitySummary: 'فرصة للمصورين وصناع المحتوى للمشاركة في حملة ترويجية لإبراز جمال وتاريخ العُلا للعالم.',
    detailedDescription: 'نبحث عن مبدعين لإنتاج محتوى عالي الجودة (صور، فيديوهات قصيرة، نصوص) عن المعالم الطبيعية والأثرية في العُلا. يتطلب العمل زيارة ميدانية للمنطقة لمدة يومين (تتكفل بها الهيئة).',
    volunteerRole: 'صانع محتوى',
    tasks: ['التقاط صور احترافية للمعالم', 'إنشاء مقاطع فيديو قصيرة (Reels)', 'كتابة نصوص جذابة للمنشورات'],
    expectedDeliverables: ['مجموعة من 20 صورة عالية الجودة', '5 مقاطع فيديو قصيرة', 'نصوص لـ 10 منشورات'],
    requiredSkills: ['التصوير الفوتوغرافي أو الفيديو', 'مهارات في المونتاج'],
    preferredSkills: ['امتلاك معدات تصوير احترافية'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-15',
    timeCommitmentPerWeek: '8 ساعات',
    timeFlexibility: TimeFlexibility.AS_AGREED,
    eligibility: { interviewRequired: true },
    benefits: ['تغطية تكاليف السفر والإقامة في العلا', 'شهادة من الهيئة الملكية', 'فرصة فريدة لتوثيق أحد أهم المواقع في المملكة'],
    socialImpact: { description: 'المساهمة في الترويج للسياحة في المملكة وجذب الزوار من جميع أنحاء العالم، مما يدعم الاقتصاد المحلي.' },
    applicantsCount: 19,
    category: OpportunityCategory.MARKETING,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1610927049444-24751475c48b?q=80&w=1974&auto=format&fit=crop',
    lat: 26.6171,
    lng: 37.9287,
    rating: 5.0,
    reviewsCount: 8,
    points: 300,
    hours: 25,
  },
    {
    id: 24,
    title: 'اختبار تطبيق جوال لشركة صحية ناشئة',
    organization: 'شركة "صحة تك"',
    workType: 'تقنية معلومات',
    workStyle: WorkStyle.REMOTE,
    commitment: '15 ساعة خلال أسبوعين',
    applicationDeadline: '2024-11-28',
    status: ApplicationStatus.OPEN,
    skillTags: ['Testing', 'QA', 'Mobile Apps'],
    isFeatured: false,
    organizationDescription: 'شركة ناشئة تعمل على تطوير تطبيقات مبتكرة في المجال الصحي.',
    opportunitySummary: 'مطلوب متطوعون مهتمون بالتقنية لتجربة النسخة التجريبية من تطبيقنا الجديد وتقديم ملاحظات لتحسين تجربة المستخدم.',
    detailedDescription: 'سيقوم المتطوعون بتحميل التطبيق على هواتفهم (iOS/Android) واستخدامه بشكل مكثف حسب سيناريوهات محددة، ثم تسجيل أي مشاكل تقنية أو اقتراحات لتحسين الواجهة في نموذج مخصص.',
    volunteerRole: 'مختبر تطبيقات (Beta Tester)',
    tasks: ['تنفيذ حالات الاختبار (Test Cases)', 'الإبلاغ عن الأخطاء (Bugs) بوضوح', 'تقديم اقتراحات لتحسين قابلية الاستخدام'],
    expectedDeliverables: ['تقرير بالأخطاء المكتشفة', 'إكمال استبيان عن تجربة الاستخدام'],
    requiredSkills: ['الدقة في الملاحظة', 'القدرة على وصف المشاكل التقنية بوضوح'],
    preferredSkills: ['خلفية في هندسة البرمجيات أو ضمان الجودة'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-02',
    timeCommitmentPerWeek: '7-8 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: {},
    benefits: ['شهادة خبرة في اختبار البرمجيات', 'الحصول على نسخة مجانية من التطبيق عند إطلاقه', 'المساهمة في تطوير منتج تقني سعودي'],
    socialImpact: { description: 'المساعدة في إطلاق تطبيق صحي عالي الجودة يمكن أن يساهم في تحسين حياة المستخدمين الصحية.' },
    applicantsCount: 50,
    category: OpportunityCategory.TECH,
    impactArea: ImpactArea.HEALTH,
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=2070&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.5,
    reviewsCount: 10,
    points: 150,
    hours: 15,
  },
  {
    id: 25,
    title: 'تقديم ملاحظات على تصميم واجهة مستخدم لمنصة حكومية',
    organization: 'هيئة الحكومة الرقمية',
    workType: 'تصميم UI/UX',
    workStyle: WorkStyle.REMOTE,
    commitment: '10 ساعات خلال أسبوع',
    applicationDeadline: '2024-11-15',
    status: ApplicationStatus.REVIEWING,
    skillTags: ['UI/UX', 'Feedback', 'Usability'],
    isFeatured: false,
    organizationDescription: 'الجهة المسؤولة عن تطوير وتحسين الخدمات الحكومية الرقمية في المملكة.',
    opportunitySummary: 'فرصة للمهتمين بتجربة المستخدم للمشاركة في مراجعة تصميم منصة حكومية جديدة قبل إطلاقها الرسمي وتقديم توصيات للتحسين.',
    detailedDescription: 'سيتم منح المتطوعين وصولاً إلى نسخة أولية من المنصة، والمطلوب هو تصفحها وإنجاز بعض المهام المحددة، ثم تعبئة استبيان مفصل حول سهولة الاستخدام ووضوح التصميم وتقديم اقتراحات بناءة.',
    volunteerRole: 'مراجع تجربة مستخدم',
    tasks: ['استكشاف جميع أقسام المنصة', 'محاولة إنجاز مهام مثل (تسجيل، بحث، تقديم طلب)', 'توثيق أي صعوبات أو نقاط غير واضحة'],
    expectedDeliverables: ['تقرير ملاحظات مفصل', 'إكمال استبيان التقييم'],
    requiredSkills: ['فهم أساسيات تجربة المستخدم (UX)', 'قدرة على النقد البناء'],
    preferredSkills: ['خبرة عملية في تصميم أو اختبار واجهات المستخدم'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-18',
    timeCommitmentPerWeek: '10 ساعات',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: { ndaRequired: true },
    benefits: ['شهادة شكر من الهيئة', 'المساهمة في تحسين الخدمات الحكومية للمواطنين', 'الاطلاع على أحدث المشاريع الرقمية الحكومية'],
    socialImpact: { description: 'تحسين تجربة المواطنين والمقيمين عند استخدام المنصات الحكومية، مما يوفر الوقت والجهد ويعزز كفاءة الخدمات.' },
    applicantsCount: 28,
    category: OpportunityCategory.DESIGN,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1559028006-448665bd7c2f?q=80&w=1974&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.8,
    reviewsCount: 6,
    points: 100,
    hours: 10,
  },
  {
    id: 26,
    title: 'توزيع السلال الغذائية للأسر المحتاجة',
    organization: 'جمعية البر الخيرية',
    workType: 'عمل ميداني',
    workStyle: WorkStyle.ONSITE,
    commitment: 'يوم واحد (5 ساعات)',
    applicationDeadline: '2024-12-10',
    status: ApplicationStatus.OPEN,
    city: 'جدة',
    skillTags: ['عمل جماعي', 'ميداني', 'اجتماعي'],
    isFeatured: false,
    organizationDescription: 'جمعية خيرية تعمل على دعم الأسر ذات الدخل المحدود في جدة.',
    opportunitySummary: 'شاركنا الأجر في توزيع السلال الغذائية على الأسر المسجلة في الجمعية قبل نهاية العام.',
    detailedDescription: 'نحتاج إلى أيادي عاملة للمساعدة في تحميل وتوزيع السلال الغذائية على سيارات المستفيدين في مقر الجمعية. عمل بسيط وأجره عظيم.',
    volunteerRole: 'عضو فريق التوزيع',
    tasks: ['تجهيز السلال الغذائية', 'المساعدة في تنظيم المستفيدين', 'توزيع السلال بشكل منظم'],
    expectedDeliverables: ['توزيع جميع السلال المخصصة لليوم'],
    requiredSkills: ['القدرة على العمل الجماعي'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-14',
    timeCommitmentPerWeek: '5 ساعات',
    timeFlexibility: TimeFlexibility.FIXED,
    eligibility: {},
    benefits: ['الأجر والثواب', 'الشعور بالرضا عن النفس'],
    socialImpact: { description: 'توفير الأمن الغذائي للأسر المحتاجة، وتخفيف العبء المالي عنهم.' },
    applicantsCount: 60,
    category: OpportunityCategory.SOCIAL,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?q=80&w=2070&auto=format&fit=crop',
    lat: 21.4858,
    lng: 39.1925,
    rating: 5.0,
    reviewsCount: 40,
    points: 70,
    hours: 5,
  },
  {
    id: 27,
    title: 'تقديم ورشة عمل عن إعادة التدوير',
    organization: 'جمعية البيئة السعودية',
    workType: 'توعية بيئية',
    workStyle: WorkStyle.ONSITE,
    commitment: '10 ساعات (تحضير + تقديم)',
    applicationDeadline: '2024-11-30',
    status: ApplicationStatus.OPEN,
    city: 'الخبر',
    skillTags: ['بيئة', 'إلقاء', 'توعية'],
    isFeatured: false,
    organizationDescription: 'جمعية تعمل على نشر الوعي البيئي في المنطقة الشرقية.',
    opportunitySummary: 'مطلوب متطوع لديه شغف بالبيئة لتقديم ورشة عمل تفاعلية لطلاب المدارس حول أهمية وكيفية إعادة التدوير.',
    detailedDescription: 'سيقوم المتطوع، بدعم من الجمعية، بإعداد وتقديم ورشة عمل لمدة ساعة في إحدى المدارس. سيتم توفير المادة العلمية الأساسية، ولكن نرحب بالإضافات الإبداعية.',
    volunteerRole: 'مقدم ورشة عمل',
    tasks: ['تخصيص المادة العلمية لتناسب الأطفال', 'تحضير أنشطة تفاعلية', 'تقديم الورشة بأسلوب ممتع'],
    expectedDeliverables: ['تقديم ورشة عمل ناجحة', 'إلهام الطلاب لتبني ممارسات إعادة التدوير'],
    requiredSkills: ['مهارات العرض والإلقاء', 'القدرة على التفاعل مع الأطفال'],
    preferredSkills: ['خلفية في العلوم البيئية'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-08',
    timeCommitmentPerWeek: '10 ساعات',
    timeFlexibility: TimeFlexibility.AS_AGREED,
    eligibility: {},
    benefits: ['شهادة خبرة في التوعية البيئية', 'تطوير مهارات الإلقاء والتحدث أمام الجمهور'],
    socialImpact: { description: 'بناء جيل جديد واعٍ بأهمية الحفاظ على البيئة، وتقليل حجم النفايات المرسلة إلى المكبات.' },
    applicantsCount: 12,
    category: OpportunityCategory.ENVIRONMENTAL,
    impactArea: ImpactArea.ENVIRONMENT,
    imageUrl: 'https://images.unsplash.com/photo-1604187351543-041571407e3c?q=80&w=1964&auto=format&fit=crop',
    lat: 26.2172,
    lng: 50.1944,
    rating: 4.9,
    reviewsCount: 5,
    points: 120,
    hours: 10,
  },
  {
    id: 28,
    title: 'متطوع دعم نفسي عبر الهاتف',
    organization: 'منصة "استمع لي"',
    workType: 'دعم نفسي',
    workStyle: WorkStyle.REMOTE,
    commitment: '40 ساعة (تدريب + مناوبات)',
    applicationDeadline: '2024-12-01',
    status: ApplicationStatus.OPEN,
    skillTags: ['استماع فعال', 'دعم نفسي', 'صحة نفسية'],
    isFeatured: true,
    organizationDescription: 'خط هاتفي غير ربحي لتقديم الدعم النفسي الأولي لمن يحتاجه.',
    opportunitySummary: 'فرصة للمتخصصين والمهتمين بالصحة النفسية لتقديم دعم أولي عبر الهاتف للأشخاص الذين يمرون بضغوطات نفسية.',
    detailedDescription: 'بعد إكمال برنامج تدريبي متخصص، سيقوم المتطوع بالرد على المكالمات وتقديم استماع فعال ودعم نفسي أولي (وليس علاجًا). العمل يتم بنظام المناوبات من المنزل.',
    volunteerRole: 'مستمع متعاطف',
    tasks: ['حضور البرنامج التدريبي بالكامل (10 ساعات)', 'الالتزام بـ 4 مناوبات شهريًا (كل مناوبة 3 ساعات)', 'تقديم الدعم وفقًا للبروتوكولات المعتمدة'],
    expectedDeliverables: ['إكمال الساعات التدريبية والمناوبات التطوعية بنجاح'],
    requiredSkills: ['مهارات استماع وتعاطف عالية', 'الالتزام بالسرية التامة'],
    preferredSkills: ['طلاب وخريجو علم النفس والخدمة الاجتماعية'],
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-10',
    timeCommitmentPerWeek: '3-4 ساعات',
    timeFlexibility: TimeFlexibility.AS_AGREED,
    eligibility: { interviewRequired: true, minimumAge: 21 },
    benefits: ['تدريب احترافي في الدعم النفسي الأولي', 'اكتساب خبرة عملية في مجال الصحة النفسية', 'شهادة معتمدة'],
    socialImpact: { description: 'توفير مساحة آمنة للأفراد للتعبير عن مشاعرهم، وقد تساهم في منع تفاقم المشاكل النفسية.' },
    applicantsCount: 33,
    category: OpportunityCategory.HEALTH,
    impactArea: ImpactArea.HEALTH,
    imageUrl: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?q=80&w=2067&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 5.0,
    reviewsCount: 14,
    points: 450,
    hours: 40,
  },
  {
    id: 29,
    title: 'إرشاد وتوجيه طلاب جامعيين مستجدين',
    organization: 'جامعة الأميرة نورة بنت عبدالرحمن',
    workType: 'إرشاد طلابي',
    workStyle: WorkStyle.HYBRID,
    commitment: '20 ساعة خلال فصل دراسي',
    applicationDeadline: '2024-10-20',
    status: ApplicationStatus.OPEN,
    city: 'الرياض',
    skillTags: ['إرشاد', 'توجيه', 'تعليم'],
    isFeatured: false,
    organizationDescription: 'برنامج الإرشاد الأكاديمي في عمادة شؤون الطالبات.',
    opportunitySummary: 'مطلوب طالبات من السنوات المتقدمة للتطوع كمرشدات للطالبات المستجدات، ومساعدتهن على التكيف مع الحياة الجامعية.',
    detailedDescription: 'ستكون كل متطوعة مسؤولة عن مجموعة صغيرة من الطالبات المستجدات، حيث ستقوم بعقد لقاءات دورية (عن بعد وحضورية) للإجابة على استفساراتهن، تعريفهن بالأنظمة الجامعية، وتقديم الدعم الأكاديمي والنفسي.',
    volunteerRole: 'مرشدة أكاديمية',
    tasks: ['التواصل الدوري مع الطالبات', 'تنظيم لقاء تعريفي', 'توجيه الطالبات للمصادر والخدمات المتاحة في الجامعة'],
    expectedDeliverables: ['مساعدة الطالبات على اجتياز الفصل الدراسي الأول بنجاح'],
    requiredSkills: ['معرفة بأنظمة الجامعة', 'مهارات تواصل جيدة', 'القدرة على بناء علاقات إيجابية'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-11-01',
    timeCommitmentPerWeek: '1-2 ساعة',
    timeFlexibility: TimeFlexibility.FLEXIBLE,
    eligibility: { interviewRequired: true },
    benefits: ['شهادة خبرة في الإرشاد الطلابي', 'تطوير المهارات القيادية', 'نقاط إضافية في المفاضلة للأنشطة الطلابية'],
    socialImpact: { description: 'تسهيل انتقال الطالبات المستجدات للحياة الجامعية، مما يقلل من نسب التعثر الأكاديمي ويزيد من اندماجهن الإيجابي.' },
    applicantsCount: 45,
    category: OpportunityCategory.EDUCATION,
    impactArea: ImpactArea.EDUCATION,
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=2070&auto=format&fit=crop',
    lat: 24.8453,
    lng: 46.7275,
    rating: 4.9,
    reviewsCount: 19,
    points: 220,
    hours: 20,
  },
  {
    id: 30,
    title: 'دعم لوجستي لمعرض الكتاب الدولي',
    organization: 'هيئة الأدب والنشر والترجمة',
    workType: 'تنظيم فعاليات',
    workStyle: WorkStyle.ONSITE,
    commitment: '16 ساعة (يومان في عطلة نهاية الأسبوع)',
    applicationDeadline: '2024-11-25',
    status: ApplicationStatus.OPEN,
    city: 'الرياض',
    skillTags: ['تنظيم', 'لوجستي', 'فعاليات'],
    isFeatured: false,
    organizationDescription: 'أحد أكبر معارض الكتب في المنطقة، ويستقطب مئات الآلاف من الزوار.',
    opportunitySummary: 'كن جزءًا من فريق عمل معرض الرياض الدولي للكتاب! فرصة للمساعدة في التنظيم وتقديم الدعم اللوجستي لضمان تجربة مميزة للزوار.',
    detailedDescription: 'سيتم توزيع المتطوعين على مهام متنوعة مثل إرشاد الزوار، المساعدة في نقاط الاستعلامات، دعم منصات التوقيع، والمساعدة في تنظيم دخول وخروج الجمهور.',
    volunteerRole: 'منظم فعالية',
    tasks: ['استقبال الزوار والإجابة على استفساراتهم', 'توجيه الجمهور إلى أجنحة دور النشر والفعاليات', 'المساعدة في تنظيم طوابير منصات التوقيع'],
    expectedDeliverables: ['ضمان سير العمل بسلاسة في المنطقة الموكلة إليك'],
    requiredSkills: ['اللباقة وحسن التعامل مع الجمهور', 'القدرة على العمل تحت الضغط'],
    experienceLevel: ExperienceLevel.BEGINNER,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-06',
    timeCommitmentPerWeek: '16 ساعة',
    timeFlexibility: TimeFlexibility.FIXED,
    eligibility: { minimumAge: 18 },
    benefits: ['شهادة مشاركة من هيئة الأدب', 'الحصول على تذكرة دخول مجانية لأيام المعرض الأخرى', 'تجربة فريدة خلف كواليس حدث ثقافي ضخم'],
    socialImpact: { description: 'المساهمة في نجاح أكبر تظاهرة ثقافية في المملكة، وتشجيع المجتمع على القراءة والاطلاع.' },
    applicantsCount: 150,
    category: OpportunityCategory.SOCIAL,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=1974&auto=format&fit=crop',
    lat: 24.7136,
    lng: 46.6753,
    rating: 4.7,
    reviewsCount: 55,
    points: 130,
    hours: 16,
  },
  {
    id: 31,
    title: 'توثيق وتصوير فعاليات موسم جدة',
    organization: 'المركز الوطني للفعاليات',
    workType: 'تصوير فوتوغرافي وفيديو',
    workStyle: WorkStyle.ONSITE,
    commitment: '30 ساعة خلال شهر الموسم',
    applicationDeadline: '2024-12-01',
    status: ApplicationStatus.OPEN,
    city: 'جدة',
    skillTags: ['تصوير', 'فيديو', 'مونتاج', 'فعاليات'],
    isFeatured: true,
    organizationDescription: 'موسم جدة هو مهرجان ترفيهي وثقافي يقام سنويًا في مدينة جدة.',
    opportunitySummary: 'فرصة للمصورين ومصوري الفيديو الموهوبين لتوثيق اللحظات المميزة في فعاليات موسم جدة المختلفة ونقل أجواء المرح للجمهور.',
    detailedDescription: 'سيقوم المتطوعون بتغطية عدد من الفعاليات المحددة (حفلات، عروض، مناطق ترفيهية)، والتقاط صور وفيديوهات عالية الجودة لاستخدامها في الحملات الإعلامية للموسم.',
    volunteerRole: 'مصور فوتوغرافي / فيديو',
    tasks: ['تصوير الفعاليات وتفاعل الجمهور', 'تسليم المواد المصورة بشكل يومي', 'عمل مونتاج بسيط لمقاطع الفيديو القصيرة'],
    expectedDeliverables: ['مجموعة من الصور والفيديوهات عالية الجودة لكل فعالية يتم تغطيتها'],
    requiredSkills: ['خبرة في التصوير الفوتوغرافي والفيديو', 'امتلاك كاميرا احترافية'],
    preferredSkills: ['خبرة في تصوير الفعاليات الكبرى'],
    experienceLevel: ExperienceLevel.EXPERT,
    requiredLanguages: ['العربية'],
    startDate: '2024-12-15',
    timeCommitmentPerWeek: '7-8 ساعات',
    timeFlexibility: TimeFlexibility.AS_AGREED,
    eligibility: { interviewRequired: true },
    benefits: ['تصريح دخول خاص لجميع فعاليات الموسم', 'نشر الصور باسم المصور في بعض المنصات', 'شهادة خبرة من المركز الوطني للفعاليات'],
    socialImpact: { description: 'نقل صورة إيجابية ومبهجة عن الفعاليات الترفيهية في المملكة، وتعزيز مكانة جدة كوجهة سياحية رائدة.' },
    applicantsCount: 25,
    category: OpportunityCategory.MARKETING,
    impactArea: ImpactArea.SOCIAL,
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=2069&auto=format&fit=crop',
    lat: 21.543333,
    lng: 39.172778,
    rating: 4.9,
    reviewsCount: 12,
    points: 280,
    hours: 30,
  }
];

export const REVIEWS: Review[] = [
  {
    id: 21,
    opportunityId: 11,
    volunteerName: 'نورة المطيري',
    volunteerImage: 'https://i.pravatar.cc/150?u=noura',
    rating: 5,
    // FIX: Corrected typo 'مشاركتi' to 'مشاركتي'.
    comment: 'تجربة احترافية ومميزة. تم تقدير مجهودنا كمصممين والمشروع كان له أثر واضح. فخورة بمشاركتي.'
  },
  {
    id: 22,
    opportunityId: 11,
    volunteerName: 'خالد الحربي',
    volunteerImage: 'https://i.pravatar.cc/150?u=khaled',
    rating: 5,
    comment: 'فرصة عظيمة لتطبيق مهارات تصميم الهوية على مشروع حقيقي. التواصل مع الجمعية كان سلسًا والهدف نبيل.'
  },
  {
    id: 23,
    opportunityId: 11,
    volunteerName: 'سارة العتيبي',
    volunteerImage: 'https://i.pravatar.cc/150?u=sara',
    rating: 5,
    comment: 'استفدت كثيرًا من هذه الفرصة، والجمعية كانت متعاونة جدًا. أنصح بها كل مصمم يريد أن يترك بصمة.'
  },
  {
    id: 24,
    opportunityId: 11,
    volunteerName: 'محمد الغامدي',
    volunteerImage: 'https://i.pravatar.cc/150?u=mohammed',
    rating: 4,
    comment: 'تجربة جيدة جدًا، أضافت الكثير لمعرض أعمالي.'
  },
  {
    id: 25,
    opportunityId: 12,
    volunteerName: 'علي الدوسري',
    volunteerImage: 'https://i.pravatar.cc/150?u=ali',
    rating: 5,
    comment: 'مبادرة رائعة ومنظمة بشكل ممتاز. شعور رائع بالمساهمة في نظافة بيئتنا.'
  },
  {
    id: 26,
    opportunityId: 13,
    volunteerName: 'ريم عبدالله',
    volunteerImage: 'https://i.pravatar.cc/150?u=reem_abdullah',
    rating: 5,
    comment: 'فريق العمل في الجمعية كان متعاونًا جدًا، والمشروع أتاح لي فرصة لتطوير مهاراتي في البرمجة وخدمة المجتمع.'
  },
];


export const BADGES: Badge[] = [
  { id: 1, name: 'سفير البيئة', icon: '🌿', description: 'لمشاركتك في 3 مبادرات بيئية' },
  { id: 2, name: 'صانع الأثر', icon: '✨', description: 'لإكمالك 50 ساعة تطوعية' },
  { id: 3, name: 'يد العطاء', icon: '❤️', description: 'للمشاركة في مبادرات اجتماعية' },
  { id: 4, name: 'مرشد الأجيال', icon: '🎓', description: 'للمساهمة في 3 مبادرات تعليمية' },
];

export const MOCK_VOLUNTEER: Volunteer = {
  id: 101,
  
  // 1. Basic Personal Information
  fullName: 'أحمد خالد الرشيد',
  email: 'ahmed@taww.sa',
  phone: '+966501234567',
  nationalId: '1234567890',
  city: 'الرياض',
  country: 'المملكة العربية السعودية',
  birthDate: '1998-05-15',
  profilePictureUrl: 'https://i.postimg.cc/43c48S58/swrt-ahmd.jpg',
  shortBio: 'مطور واجهات أمامية ومصمم UI/UX شغوف بتحويل الأفكار إلى تجارب مستخدم ملموسة. أسعى لاستغلال مهاراتي التقنية في المساهمة بمبادرات مجتمعية ذات أثر إيجابي.',
  preferredLanguage: 'العربية',
  
  // 2. Qualifications and Academic Background
  academicQualification: AcademicQualification.BACHELOR,
  specialization: 'علوم الحاسب',
  university: 'جامعة شقراء',
  graduationYear: '2023',
  
  // 3. Work and Professional Experience
  currentJobTitle: 'مطوّر واجهات أمامية (Frontend Developer)',
  experienceYears: ExperienceYears.ONE_TO_THREE,
  skills: ['React', 'TypeScript', 'UI/UX Design', 'Next.js', 'Tailwind CSS', 'Node.js'],
  tools: ['Figma', 'VS Code', 'Git', 'Jira'],
  languages: [
    { language: 'العربية', level: LanguageLevel.NATIVE },
    { language: 'الإنجليزية', level: LanguageLevel.ADVANCED }
  ],
  certifications: ['شهادة Google UX Design الاحترافية'],
  portfolioLink: 'https://github.com/example-user',
  linkedinUrl: 'https://www.linkedin.com/in/example-user',

  // 4. Volunteering Interests and Fields
  preferredFields: ['تقنية', 'تصميم', 'تعليم'],
  interestedSectors: [ImpactArea.YOUTH, ImpactArea.EDUCATION, ImpactArea.ENVIRONMENT],
  preferredWorkType: PreferredWorkType.REMOTE,
  commitmentDuration: CommitmentDuration.MEDIUM,
  availableHoursPerWeek: '5-10 ساعات',
  availability: 'مساءً وعطلات نهاية الأسبوع',

  // 5. Readiness and Commitment
  hasVolunteeredBefore: true,
  previousExperience: 'تطوعت في تطوير موقع إلكتروني لمبادرة طلابية محلية.',
  motivation: 'أؤمن بأهمية رد الجميل للمجتمع، وأرى في التطوع الاحترافي فرصة مثالية لتنمية مهاراتي وخدمة الآخرين في نفس الوقت.',
  commitmentLevel: 5,
  availabilityDate: '2024-09-01',

  // 6. Consents and Agreements
  agreedToPolicy: true,
  agreedToNDA: true,
  agreedToShareData: true,
  agreedToPublishName: true,

  // 7. Platform-managed data
  registeredOpportunities: [],
  badges: [],
  hours: 0,
  points: 0,
  reviewedOpportunityIds: [],
};

// Simplified leaderboard data to match new Volunteer type
export const LEADERBOARD_VOLUNTEERS: Volunteer[] = [
  { ...MOCK_VOLUNTEER, id: 201, fullName: 'سارة العتيبي', university: 'جامعة الأميرة نورة بنت عبدالرحمن', profilePictureUrl: 'https://i.pravatar.cc/150?u=sara', hours: 152, points: 1850, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 202, fullName: 'محمد الغامدي', university: 'جامعة الملك سعود', profilePictureUrl: 'https://i.pravatar.cc/150?u=mohammed', hours: 140, points: 1720, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 203, fullName: 'فاطمة الزهراني', university: 'جامعة الملك عبدالعزيز', profilePictureUrl: 'https://i.pravatar.cc/150?u=fatima', hours: 135, points: 1680, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 204, fullName: 'عبدالله الشهري', university: 'جامعة الملك فهد للبترول والمعادن', profilePictureUrl: 'https://i.pravatar.cc/150?u=abdullah', hours: 121, points: 1500, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 205, fullName: 'نورة المطيري', university: 'جامعة الأميرة نورة بنت عبدالرحمن', profilePictureUrl: 'https://i.pravatar.cc/150?u=noura', hours: 115, points: 1450, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 206, fullName: 'خالد الحربي', university: 'جامعة القصيم', profilePictureUrl: 'https://i.pravatar.cc/150?u=khaled', hours: 98, points: 1230, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 207, fullName: 'ريم القحطاني', university: 'جامعة الملك سعود', profilePictureUrl: 'https://i.pravatar.cc/150?u=reem', hours: 85, points: 1100, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 208, fullName: 'سلطان الدوسري', university: 'جامعة الإمام محمد بن سعود الإسلامية', profilePictureUrl: 'https://i.pravatar.cc/150?u=sultan', hours: 50, points: 750, shortBio: '' },
  { ...MOCK_VOLUNTEER, hours: 25, points: 300 }, // Current user
  { ...MOCK_VOLUNTEER, id: 209, fullName: 'جنى العمودي', university: 'جامعة الفيصل', profilePictureUrl: 'https://i.pravatar.cc/150?u=jana', hours: 12, points: 150, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 210, fullName: 'فيصل الأحمد', university: 'جامعة الملك سعود', profilePictureUrl: 'https://i.pravatar.cc/150?u=faisal', hours: 160, points: 1900, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 211, fullName: 'لمى تركي', university: 'جامعة الأميرة نورة بنت عبدالرحمن', profilePictureUrl: 'https://i.pravatar.cc/150?u=lama', hours: 130, points: 1600, shortBio: '' },
  { ...MOCK_VOLUNTEER, id: 212, fullName: 'يزيد الراجحي', university: 'جامعة اليمامة', profilePictureUrl: 'https://i.pravatar.cc/150?u=yazeed', hours: 110, points: 1400, shortBio: '' },

];


export const NAV_LINKS = [
  { name: 'الرئيسية', path: '/', icon: 'HomeIcon' },
  { name: 'الفرص', path: '/opportunities', icon: 'ListIcon' },
  { name: 'لوحة المراكز', path: '/leaderboard', icon: 'LeaderboardIcon' },
  { name: 'المساعد الذكي', path: '/ai-assistant', icon: 'SparklesIcon' },
  { name: 'ملفي', path: '/profile', icon: 'UserIcon' },
];

export const SAUDI_UNIVERSITIES = [
  "جامعة الملك سعود",
  "جامعة الملك عبدالعزيز",
  "جامعة الملك فهد للبترول والمعادن",
  "جامعة أم القرى",
  "جامعة الإمام محمد بن سعود الإسلامية",
  "جامعة الأميرة نورة بنت عبدالرحمن",
  "جامعة الملك عبدالله للعلوم والتقنية",
  "جامعة الفيصل",
  "جامعة طيبة",
  "جامعة القصيم",
  "جامعة جازان",
  "جامعة تبوك",
  "جامعة نجران",
  "جامعة الحدود الشمالية",
  "جامعة الجوف",
  "جامعة شقراء",
  "جامعة المجمعة",
  "جامعة اليمامة"
];